In [ ]:
import cv2 as cv
import numpy as np

def access_pixels(image):
    print(image.shape)
    height = image.shape[0]
    width = image.shape[1]
    channels = image.shape[2]
    print("width: %s, height: %s, channels: %s"%(width, height, channels))
    for row in range(height):
        for col in range(width):
            for c in range(channels):
                pv = image[row, col, c]
                image[row, col, c] = 255-pv   # 图像反转
    cv.imshow("pixels_demo",image)

# 我们会发现像素取反这个过程花费的时间很多，这里有一个快速的方法
# 20ms 就解决了。 原因：python是解释执行，通过inverse是C的代码，速度更快
# 因为opencv自带的API， 它是用C写的
def inverse(image):
    dat = cv.bitwise_not(image)
    cv.imshow("inverse demo", dat)
    

def create_image():
    '''
    # 下面是对 多通道图的单个通道 来进行操作
    img = np.zeros([400,400,3], np.uint8)
    # 修改通道值：opencv默认通道是BGR。纯蓝色：R0 G0 B255
    img[:, :, 0] = np.ones([400,400])*255   # 第一个通道全部乘以255
    cv.imshow("new_image", img)
    '''
    '''
    # 尝试多通道一起操作，要一起操作就意味着只有一个通道，那么就是灰度图
    img = np.zeros([400, 400, 1], np.uint8)
    img[:, :, 0] = np.ones([400, 400]) * 127
    cv.imshow("new image", img)
    # 至此我们都是初始化很大的
    '''
    # 我们可以来尝试初始化小的, np.float32 都可以运行
    m1 = np.ones([3,3],np.uint8)   # 尝试一下截断
    m1.fill(122222)
    print(m1)
    
    m2 =m1.reshape(1,9)
    print(m2)
    
print("------------Hello Python----------")

src = cv.imread("/home/anaconda/桌面/自学OpenCV/src/lena.jpg")
cv.namedWindow("input image", cv.WINDOW_AUTOSIZE)
cv.imshow("First_pic",src)

t1 = cv.getTickCount()  # 获取当前电脑时钟滴答数
create_image()
inverse(src)

t2 = cv.getTickCount()
time = (t2 - t1)/cv.getTickFrequency()  
# 函数执行前后滴答数之差与滴答频率之比为前后时间差
print("time: %s ms"%(time * 1000))
cv.waitKey(0)

------------Hello Python----------
[[110 110 110]
 [110 110 110]
 [110 110 110]]
[[110 110 110 110 110 110 110 110 110]]
time: 22.484793 ms


In [25]:
import numpy as np
print(np.zeros([4,5,3],int))
a = np.zeros([2,2,2],int)
print(a)

a[:,0,:] = np.ones([2,2])*25
print(a)

print(np.zeros([5,4,3]))

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[25 25]
  [ 0  0]]

 [[25 25]
  [ 0  0]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
