In [2]:
import cv2 as cv
import numpy as np

In [ ]:
def add_demo(m1, m2):
    dat = cv.add(m1,m2)
    cv.imshow("add_demo", dat)
    
def subtract_demo(m1, m2):
    dat = cv.subtract(m1,m2)
    cv.imshow("subtract_demo", dat)
    
def divide_demo(m1, m2):    # 这个出来一般都是一片漆黑，因为除完后值一般很小
    dat = cv.divide(m1,m2)
    cv.imshow("divide_demo", dat)

def multiply_demo(m1, m2):  # 乘完之后结果变得很大，0和别人相乘就会变得很小
    dat = cv.multiply(m1,m2)
    cv.imshow("multiply_demo", dat)
    
def others(m1, m2):    # 求每个通道的均值,第四个参数0.0是alpha通道，控制透明度
    M1 = cv.mean(m1)
    M2 = cv.mean(m2)
    M1,dev1 = cv.meanStdDev(m1)  # 方差高说明像素之间差异比较大，对比度越大
    M2,dev2 = cv.meanStdDev(m2)
    
    print(M1)
    print(M2)
    
    print(dev1)
    print(dev2)
    
    # 重新定义一个图片，与原来尺寸一样
    h, w = m1.shape[:2]  # 切片[]包首不包尾，[:2] = 0, 1. 将行列赋值给h，w
    img = np.zeros([h,w], np.uint8)
    
print("------------Hello Python----------")

src1 = cv.imread("/home/anaconda/桌面/自学OpenCV/src/01.jpg")
src2 = cv.imread("/home/anaconda/桌面/自学OpenCV/src/02.jpg")

print(src1.shape)
print(src2.shape)

cv.namedWindow("input image", cv.WINDOW_AUTOSIZE)
cv.imshow("image1",src1)
cv.imshow("image2",src2)

add_demo(src1, src2)
subtract_demo(src1, src2)
divide_demo(src1, src2)
multiply_demo(src1, src2)   
# 其实linux这个原图中字母周围不一定完全是0,黑白交界处可能是很小很小的值
# 经过乘法后，就有一个值，就产生了这种锯齿状效果
# linux乘法完后中间还有蓝色，（255*大于一的值一定会截断啊？）
# 因为windows图标上有黑色的阴影部分，这个部分的值小于1,所以出现蓝绿色

others(src1, src2)

cv.waitKey(0)
cv.destroyAllWindows()

------------Hello Python----------
(240, 320, 3)
(240, 320, 3)
[[15.0128125]
 [15.0128125]
 [15.0128125]]
[[128.05269531]
 [109.60858073]
 [ 62.55748698]]
[[58.14062149]
 [58.14062149]
 [58.14062149]]
[[54.60093646]
 [45.52335089]
 [50.01800277]]
