In [1]:
import cv2 as cv
import numpy as np

def video_demo():
    capture = cv.VideoCapture(0)
    while(True):
        ret, frame = capture.read()
        frame = cv.flip(frame,1)  # 这是镜像正过来，一般视频中都是反向的。
        cv.imshow("video", frame)
        c = cv.waitKey(50)
        if c == 27:
            break

def get_image_info(image):
    print(type(image))
    print(image.shape)
    print(image.size)
    print(image.dtype)
    pixel_data = np.array(image)
    print(pixel_data)
 

print("------------Hello Python----------")

src = cv.imread("1.jpg")
cv.namedWindow("input image", cv.WINDOW_AUTOSIZE)
cv.imshow("First_pic",src)
cv.waitKey(0)
get_image_info(src)

cv.destroyAllWindows()   # 这里是destroy all，若我们只想销毁某一个窗口，就要给他传参

------------Hello Python----------
<class 'numpy.ndarray'>
(126, 189, 3)
71442
uint8
[[[ 80 146 134]
  [ 91 161 148]
  [102 177 163]
  ...
  [131 181 163]
  [146 190 173]
  [104 140 123]]

 [[ 88 160 147]
  [111 186 172]
  [ 71 152 137]
  ...
  [116 168 150]
  [ 66 111  94]
  [ 74 114  96]]

 [[ 65 150 135]
  [121 209 193]
  [ 71 163 146]
  ...
  [ 49 105  86]
  [ 81 131 113]
  [176 220 203]]

 ...

 [[  1  24  10]
  [ 19  44  30]
  [ 40  63  49]
  ...
  [ 53  76  68]
  [ 50  73  65]
  [ 49  71  66]]

 [[ 10  30  18]
  [ 10  32  20]
  [  2  22  10]
  ...
  [ 61  82  74]
  [ 56  79  71]
  [ 55  77  72]]

 [[ 17  37  25]
  [ 24  44  32]
  [  9  29  17]
  ...
  [ 62  83  75]
  [ 60  81  73]
  [ 55  77  72]]]
